---
apiVersion: v1
kind: Service
metadata:
  name: front-nginx
  labels:
    app: front-nginx
    tier: backend
    version: "1.0"
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: front-nginx
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nginx
  labels:
    app: front-nginx
    tier: backend
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nginx
      tier: backend
      version: "1.0"
  template:
    metadata:
      labels:
        app: front-nginx
        tier: backend
        version: "1.0"
    spec:
      containers:
      - name: nginx-end
        image: ccr.ccs.tencentyun.com/shuhe/nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-front
spec:
  rules:
  - host: $EnvName$-nginx-front.app.8slan.com
    http:
      paths:
      - backend:
          serviceName: front-nginx
          servicePort: 80
        path: / 