---
apiVersion: v1
kind: Service
metadata:
  name: front-nginx
  labels:
    app: front-nginx
    tier: frontend
    version: "1.0"
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: front-nginx
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nginx
  labels:
    app: front-nginx
    tier: frontend
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nginx
      tier: frontend
      version: "1.0"
  template:
    metadata:
      labels:
        app: front-nginx
        tier: frontend
        version: "1.0"
    spec:
      containers:
        - name: front-nginx
          image: ccr.ccs.tencentyun.com/shuhe/nginx:stable
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100M
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-nginx
spec:
  rules:
    - host: $EnvName$-nginx-front.app.8slan.com
      http:
        paths:
          - frontend:
              serviceName: front-nginx
              servicePort: 80
            path: /
