---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: backend
    version: "{{.nginxVersion}}"
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
      version: "{{.nginxVersion}}"
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
        version: "{{.nginxVersion}}"
    spec:
      containers:
      - name: nginx-test
        image: ccr.ccs.tencentyun.com/trial/nginx-test:20210722155219-2-master
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-frontend
spec:
  rules:
  - host: $EnvName$-$Product$-3-nginx-frontend.{{.ingress}}.8slan.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
